name: 'Weblate sync'
description: 'Synchronizes i18n changes with weblate'

inputs:
  SERVER_URL:
    description: 'Weblate server URL'
    required: true
  TOKEN:
    description: 'API token for weblate'
    required: true
  PROJECT:
    description: 'Project name in weblate'
    required: true
  FILE_FORMAT:
    description: 'Translation files format'
    required: false
    default: 'i18next'
  KEYSETS_PATH:
    required: false
    default: 'src/i18n-keysets'
  MASTER_BRANCH:
    required: false
    default: 'main'
  MAIN_LANGUAGE:
    required: failse
    default: 'en'
  GITHUB_TOKEN:
    description: 'Token for creating comments in pull request'
    required: true

runs:
  using: 'node20'
  main: dist/index.js
