name: 'Weblate sync'
description: 'Synchronizes i18n changes with weblate'

inputs:
  SERVER_URL:
    description: 'Weblate server URL'
    required: true
  TOKEN:
    description: 'API token for weblate'
    required: true
  PROJECT:
    description: 'Project name in weblate'
    required: true
  FILE_FORMAT:
    description: 'Translation files format'
    required: false
    default: 'i18next'
  KEYSETS_PATH:
    required: false
    default: 'src/i18n-keysets'

runs:
  using: 'node20'
  main: dist/index.js
