name: 'Weblate sync'
description: 'Synchronizes i18n changes with weblate'

inputs:
  serverUrl:
    description: 'Weblate server URL'
    required: true
  token:
    description: 'API token for weblate'
    required: true
  project:
    description: 'Project name in weblate'
    required: true
  fileFormat:
    description: 'Translation files format'
    required: false
    default: 'i18next'

runs:
  using: 'node20'
  main: dist/index.js
